#!/usr/bin/perl

use strict;
use warnings;
use criticism;
use Config::File;
use Getopt::Long;
use Pod::Usage;

# READ CONFIG
# -----------
# LAST_NAMES_URL
#   "http://www.census.gov/genealogy/www/data/1990surnames/dist.all.last"
# FIRST_NAMES_FEMALE_URL
#   "http://www.census.gov/genealogy/www/data/1990surnames/dist.female.first"
# FIRST_NAMES_MALE_URL
#   "http://www.census.gov/genealogy/www/data/1990surnames/dist.male.first"
# EMAIL_INBOX_URL
#   "http://mailinator.com/inbox.jsp?to="
# EMAIL_ADDRESS_AFFIX
#   "mailinator.com "
# PASSWORD_LENGTH
#   6

# READ GETOPT
# -----------
# h,help                Display help
# n,name                Generate full name
# m,email               Generate email
# p,password[=length]   Generate password
# u,username            Generate username
# v,version             Display version

# CHECK FOR DATA, DOWNLOAD

# GENERATE ACCOUNT
